COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-7г-2	2026-03-27	[{"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Информатика", "activity": "Урок"}, {"grade": 5, "subject": "Биология", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}]
stu-7г-2	2026-03-30	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-7г-6	2026-03-13	[{"grade": 4, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Биология", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}]
stu-7г-2	2026-03-31	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Физика", "activity": "Урок"}]
stu-7г-3	2026-03-02	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-7г-3	2026-03-03	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Физика", "activity": "Урок"}]
stu-7г-3	2026-03-04	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Химия", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Информатика", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}]
stu-7г-3	2026-03-05	[{"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 2, "subject": "История", "activity": "Урок"}, {"grade": 5, "subject": "Обществознание", "activity": "Урок"}, {"grade": 4, "subject": "Биология", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}]
stu-7г-3	2026-03-06	[{"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Информатика", "activity": "Урок"}, {"grade": 2, "subject": "Биология", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}]
stu-7г-3	2026-03-09	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-7г-3	2026-03-10	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Физика", "activity": "Урок"}]
stu-7г-3	2026-03-11	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Информатика", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}]
\.
