COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-2б-15	2026-03-17	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-2б-15	2026-03-18	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Музыка", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}]
stu-2б-15	2026-03-19	[{"grade": 5, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 4, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Музыка", "activity": "Урок"}]
stu-2б-15	2026-03-20	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Изобразительное искусство", "activity": "Урок"}]
stu-2б-15	2026-03-23	[{"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}]
stu-2б-15	2026-03-24	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-2б-15	2026-03-25	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Музыка", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}]
stu-2б-15	2026-03-26	[{"grade": 4, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 4, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 2, "subject": "История", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Музыка", "activity": "Урок"}]
stu-2б-15	2026-03-27	[{"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Изобразительное искусство", "activity": "Урок"}]
stu-2б-15	2026-03-30	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
stu-2б-15	2026-03-31	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-2б-16	2026-03-02	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
\.
