COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-1г-8	2026-03-09	[{"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-10	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-11	[{"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Музыка", "activity": "Урок"}, {"grade": 5, "subject": "История", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-12	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Музыка", "activity": "Урок"}, {"grade": 5, "subject": "Изобразительное искусство", "activity": "Урок"}]
stu-1г-8	2026-03-13	[{"grade": 4, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 4, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-1г-8	2026-03-16	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-17	[{"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-18	[{"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-19	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 2, "subject": "Музыка", "activity": "Урок"}, {"grade": 5, "subject": "Изобразительное искусство", "activity": "Урок"}]
stu-1г-8	2026-03-20	[{"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 2, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}]
stu-1г-8	2026-03-23	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-1г-8	2026-03-24	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
\.
