COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-7в-2	2026-03-10	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Биология", "activity": "Урок"}]
stu-7в-2	2026-03-11	[{"grade": 2, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}]
stu-7в-2	2026-03-12	[{"grade": 3, "subject": "Обществознание", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}]
stu-7в-2	2026-03-13	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 5, "subject": "История", "activity": "Урок"}]
stu-7в-2	2026-03-16	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}]
stu-7в-2	2026-03-17	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Биология", "activity": "Урок"}]
stu-7в-2	2026-03-18	[{"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 2, "subject": "Информатика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-7в-2	2026-03-19	[{"grade": 3, "subject": "Обществознание", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 4, "subject": "Химия", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Информатика", "activity": "Урок"}]
stu-7в-2	2026-03-20	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 5, "subject": "Биология", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}]
stu-7в-2	2026-03-23	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
stu-7в-2	2026-03-24	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-7в-2	2026-03-25	[{"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Информатика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
\.
