COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-4г-2	2026-03-20	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}]
stu-4г-2	2026-03-23	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-4г-2	2026-03-24	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-4г-2	2026-03-25	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-4г-2	2026-03-26	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 5, "subject": "Музыка", "activity": "Урок"}, {"grade": 3, "subject": "Физическая культура", "activity": "Урок"}]
stu-4г-2	2026-03-27	[{"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 2, "subject": "Труд (технология)", "activity": "Урок"}]
stu-4г-2	2026-03-31	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}]
stu-4г-3	2026-03-02	[{"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-4г-3	2026-03-03	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-4г-3	2026-03-04	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "История", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-4г-3	2026-03-05	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 4, "subject": "Музыка", "activity": "Урок"}]
stu-4г-3	2026-03-06	[{"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}]
\.
