COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-4б-20	2026-03-30	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
stu-4б-20	2026-03-31	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-4в-1	2026-03-02	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}]
stu-4в-1	2026-03-03	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-4в-1	2026-03-04	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Музыка", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-4в-1	2026-03-05	[{"grade": 4, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}]
stu-4в-1	2026-03-06	[{"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Музыка", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}]
stu-4в-1	2026-03-09	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}]
stu-4в-1	2026-03-10	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-4в-1	2026-03-11	[{"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 2, "subject": "Музыка", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-4в-1	2026-03-12	[{"grade": 3, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-4в-1	2026-03-13	[{"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Музыка", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}]
\.
