COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-6а-18	2026-03-24	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Обществознание", "activity": "Урок"}]
stu-6а-18	2026-03-25	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}]
stu-6а-18	2026-03-26	[{"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Биология", "activity": "Урок"}, {"grade": 2, "subject": "География", "activity": "Урок"}, {"grade": 4, "subject": "Музыка", "activity": "Урок"}, {"grade": 4, "subject": "Обществознание", "activity": "Урок"}]
stu-6а-18	2026-03-27	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Биология", "activity": "Урок"}, {"grade": 3, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}]
stu-6а-18	2026-03-30	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-6а-18	2026-03-31	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Обществознание", "activity": "Урок"}]
stu-6а-19	2026-03-02	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}]
stu-6а-19	2026-03-03	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Обществознание", "activity": "Урок"}]
stu-6а-19	2026-03-04	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "История", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}]
stu-6б-6	2026-03-30	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
stu-6а-19	2026-03-05	[{"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Биология", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}, {"grade": 4, "subject": "Музыка", "activity": "Урок"}]
stu-6а-19	2026-03-06	[{"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Биология", "activity": "Урок"}, {"grade": 5, "subject": "Изобразительное искусство", "activity": "Урок"}, {"grade": 4, "subject": "Информатика", "activity": "Урок"}]
\.
