COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-9б-7	2026-03-03	[{"grade": 4, "subject": "Физика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}, {"grade": 4, "subject": "Химия", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-9б-7	2026-03-04	[{"grade": 5, "subject": "Обществознание", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 2, "subject": "Физика", "activity": "Урок"}]
stu-9б-7	2026-03-05	[{"grade": 5, "subject": "Информатика", "activity": "Урок"}, {"grade": 4, "subject": "География", "activity": "Урок"}, {"grade": 2, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}, {"grade": 4, "subject": "Обществознание", "activity": "Урок"}, {"grade": 5, "subject": "Биология", "activity": "Урок"}]
stu-9б-7	2026-03-06	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}]
stu-9б-7	2026-03-09	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
stu-9б-7	2026-03-10	[{"grade": 4, "subject": "Физика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}, {"grade": 4, "subject": "Химия", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-9б-7	2026-03-11	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Биология", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Физика", "activity": "Урок"}]
stu-9б-7	2026-03-12	[{"grade": 4, "subject": "Информатика", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}, {"grade": 2, "subject": "История", "activity": "Урок"}, {"grade": 3, "subject": "Обществознание", "activity": "Урок"}, {"grade": 5, "subject": "Биология", "activity": "Урок"}]
stu-9б-7	2026-03-13	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}]
stu-9б-7	2026-03-16	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}]
stu-9б-7	2026-03-17	[{"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "Химия", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}]
stu-9б-7	2026-03-18	[{"grade": 4, "subject": "Обществознание", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Биология", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 2, "subject": "Физика", "activity": "Урок"}]
\.
