COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-8б-9	2026-03-25	[{"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}, {"grade": 2, "subject": "География", "activity": "Урок"}]
stu-8б-9	2026-03-26	[{"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}, {"grade": 4, "subject": "Биология", "activity": "Урок"}]
stu-8б-9	2026-03-27	[{"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "Труд (технология)", "activity": "Урок"}]
stu-8б-9	2026-03-30	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-8б-9	2026-03-31	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 2, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}]
stu-8б-10	2026-03-02	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-8б-10	2026-03-03	[{"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 2, "subject": "Математика", "activity": "Урок"}, {"grade": 2, "subject": "Обществознание", "activity": "Урок"}]
stu-8б-10	2026-03-04	[{"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}, {"grade": 5, "subject": "История", "activity": "Урок"}]
stu-8б-10	2026-03-05	[{"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 3, "subject": "Информатика", "activity": "Урок"}, {"grade": 5, "subject": "Биология", "activity": "Урок"}, {"grade": 4, "subject": "Обществознание", "activity": "Урок"}]
stu-8б-10	2026-03-06	[{"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Химия", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "Труд (технология)", "activity": "Урок"}]
stu-8б-10	2026-03-09	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-8б-10	2026-03-10	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Обществознание", "activity": "Урок"}]
\.
