COPY public.grade_history_detail (child_id, date_iso, items_json) FROM stdin;
stu-8а-6	2026-03-19	[{"grade": 5, "subject": "Биология", "activity": "Урок"}, {"grade": 3, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}, {"grade": 2, "subject": "Химия", "activity": "Урок"}]
stu-8а-6	2026-03-20	[{"grade": 2, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 4, "subject": "История", "activity": "Урок"}, {"grade": 3, "subject": "География", "activity": "Урок"}, {"grade": 4, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Обществознание", "activity": "Урок"}]
stu-8а-6	2026-03-23	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-8а-6	2026-03-24	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 5, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Химия", "activity": "Урок"}]
stu-8а-6	2026-03-25	[{"grade": 4, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "История", "activity": "Урок"}, {"grade": 5, "subject": "Обществознание", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}]
stu-8а-6	2026-03-26	[{"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}, {"grade": 4, "subject": "Химия", "activity": "Урок"}]
stu-8а-6	2026-03-27	[{"grade": 3, "subject": "Труд (технология)", "activity": "Урок"}, {"grade": 5, "subject": "История", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Обществознание", "activity": "Урок"}]
stu-8а-6	2026-03-30	[{"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}]
stu-8а-6	2026-03-31	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 2, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Химия", "activity": "Урок"}]
stu-8а-7	2026-03-02	[{"grade": 2, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Математика", "activity": "Урок"}, {"grade": 4, "subject": "Математика", "activity": "Урок"}, {"grade": 5, "subject": "Литература", "activity": "Урок"}]
stu-8в-5	2026-03-13	[{"grade": 3, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Химия", "activity": "Урок"}, {"grade": 5, "subject": "География", "activity": "Урок"}, {"grade": 3, "subject": "Физика", "activity": "Урок"}, {"grade": 5, "subject": "Информатика", "activity": "Урок"}]
stu-8а-7	2026-03-03	[{"grade": 5, "subject": "Литература", "activity": "Урок"}, {"grade": 5, "subject": "Физическая культура", "activity": "Урок"}, {"grade": 3, "subject": "Иностранный язык", "activity": "Урок"}, {"grade": 4, "subject": "Литература", "activity": "Урок"}, {"grade": 3, "subject": "Математика", "activity": "Урок"}, {"grade": 3, "subject": "Химия", "activity": "Урок"}]
\.
